services:
  mkdocs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mkdocs-server
    volumes:
      - ./docs:/docs/docs
      - ./mkdocs.yml:/docs/mkdocs.yml
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - 8000:8000
