nav:
- Home: index.md
- Breaking Down Problems: breaking-down-problems.md
- Smaller PRs: why-smaller-prs-matter.md
- Debugging Skills: debugging-skills.md
- Refactoring Code: refactoring-code.md
- Logging: logging.md
- Comments in Code: comments.md
- Instrumenting Code: instrumenting.md
- Why Use Containers: why-use-containers.md
hide: true